name: payvor
description: Payvor Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  shared_preferences: ^0.5.12+2
  dio: ^3.0.10
  provider: ^4.0.5
  cached_network_image: ^2.3.3
  shimmer: ^1.1.2
  flutter_svg: ^0.19.3
  webview_flutter: ^1.0.7
  country_pickers: ^2.0.0
  pin_view: ^1.0.1
  lottie: ^0.6.0
  visibility_detector: ^0.1.5
  flutter_facebook_login: ^3.0.0
  twitter_login: ^2.1.0
  flutter_webview_plugin: ^0.3.11
  quiver: ^2.1.5
  #  uni_links: ^0.4.0
  flutter_xlider: ^3.3.1
#  flutter_twitter: ^1.1.3
  image_picker: ^0.6.3+4
  image_cropper: ^1.2.1
  sqflite:
  share: ^0.6.5+4
  flutter_html: ^0.11.1
  curved_navigation_bar: ^0.3.1
  flutter_slidable: ^0.5.7
  flutter_linkify: ^2.1.0
  flutter_rating_bar: ^3.2.0+1
  cloud_firestore:
  firebase_storage:
  firebase_messaging:
  firebase_auth:
  firebase_core:
  url_launcher: ^6.0.2
#  stripe_payment: ^1.0.10
  flutter_switch: ^0.2.2
  flutter_local_notifications:
  app_review:
  flutter_email_sender: ^5.0.0
  sign_in_with_apple: ^3.0.0




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/
    - assets/png/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CircularStd-Black
      fonts:
        - asset: assets/fonts/CircularStd-Black.otf
    - family: CircularStd-BlackItalic
      fonts:
        - asset: assets/fonts/CircularStd-BlackItalic.otf
    - family: CircularStd-Bold
      fonts:
        - asset: assets/fonts/CircularStd-Bold.otf
    - family: CircularStd-BoldItalic
      fonts:
        - asset: assets/fonts/CircularStd-BoldItalic.otf
    - family: CircularStd-Book
      fonts:
        - asset: assets/fonts/CircularStd-Book.otf
    - family: CircularStd-BookItalic
      fonts:
        - asset: assets/fonts/CircularStd-BookItalic.otf
    - family: CircularStd-Medium
      fonts:
        - asset: assets/fonts/CircularStd-Medium.otf
    - family: CircularStd-MediumItalic
      fonts:
        - asset: assets/fonts/CircularStd-MediumItalic.otf




  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
